export const SET_FULLNAME_INPUT = 'set_fullname_input'
export const SET_DAYOFBIRTH_INPUT = 'set_dayofbirth_input'
export const SET_HOMETOWN_INPUT = 'set_hometown_input'
export const SET_FIELD_INPUT = 'set_field_input'
export const ADD_STUDENT = 'add_student'
export const UPDATE_STUDENT = 'update_student'
export const DELETE_STUDENT = 'delete_student'
export const SET_IMAGE_INPUT = 'set_image_input'